name: Image Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "IMAGE TEST WORKFLOW IS RUNNING"

      - name: Python test
        run: python --version

      - name: Install Gemini
        run: pip install google-genai
